[package]
name = "app"
version = "0.1.1"
description = "Clipper by AW"
authors = ["Anuradha Wickramarachchi <anuradhawick@gmail.com>"]
license = "GPL 3.0"
repository = "https://github.com/anuradhawick/clipper"
default-run = "app"
edition = "2021"
rust-version = "1.81.0"

[build-dependencies]
tauri-build = { version = "2.0.1", features = [] }

[dependencies]
serde_json = "1.0.128"
serde = { version = "1.0.210", features = ["derive"] }
tauri = { version = "2.0.1", features = ["macos-private-api", "tray-icon"] }
tauri-plugin-positioner = "2.0.1"
arboard = "3.4.1"
open = "5.3.0"
tokio = { version = "1.38.0", features = ["full"] }
uuid = { version = "1.10.0", features = ["v4"] }
sqlx = { version = "0.8.2", features = ["sqlite", "runtime-tokio-rustls"] }
chrono = "0.4.31"
tauri-plugin-shell = "2.0.1"
